import React from 'react';
import { Sparkles, ShieldCheck, Lock, Cpu } from 'lucide-react';

export default function Footer({ setActiveTab }) {
  return (
    <footer className="mt-20 border-t border-white/10 bg-[#060911] text-slate-400 py-12 px-4 lg:px-8">
      <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
        
        {/* Col 1 */}
        <div className="md:col-span-2">
          <div className="flex items-center gap-2.5 mb-3">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-indigo-600 to-pink-500 flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <span className="font-extrabold text-xl text-white font-['Outfit'] uppercase tracking-wider">CREDOMETRICS AI</span>
          </div>
          <p className="text-xs text-slate-400 max-w-md leading-relaxed mb-4">
            Next-generation Gen-AI WealthTech platform. Transforming social media hype, finfluencer noise, and fragmented investments into personalized, actionable risk profiling, net worth tracking, and goal-based SIP advisory.
          </p>
          <div className="flex items-center gap-4 text-xs font-semibold text-slate-400">
            <span className="flex items-center gap-1.5 text-emerald-400">
              <ShieldCheck className="w-4 h-4" /> SEC/SEBI Framework Aligned
            </span>
            <span className="flex items-center gap-1.5 text-indigo-400">
              <Cpu className="w-4 h-4" /> Groq LLM Inference Engine
            </span>
          </div>
        </div>

        {/* Col 2 */}
        <div>
          <h4 className="text-sm font-bold text-white mb-3">Platform Navigation</h4>
          <ul className="space-y-2 text-xs">
            <li>
              <button onClick={() => setActiveTab('landing')} className="hover:text-indigo-400 transition-colors">
                Landing & Feature Overview
              </button>
            </li>
            <li>
              <button onClick={() => setActiveTab('dashboard')} className="hover:text-indigo-400 transition-colors">
                Consolidated Portfolio Tracker
              </button>
            </li>
            <li>
              <button onClick={() => setActiveTab('analyzer')} className="hover:text-emerald-400 transition-colors">
                AI Social Hype Analyzer
              </button>
            </li>
            <li>
              <button onClick={() => setActiveTab('goals')} className="hover:text-pink-400 transition-colors">
                Goal SIP Calculator & Advisory
              </button>
            </li>
          </ul>
        </div>

        {/* Col 3 */}
        <div>
          <h4 className="text-sm font-bold text-white mb-3">Security & Compliance</h4>
          <p className="text-xs text-slate-500 leading-relaxed mb-3">
            Financial analytics generated by CredoMetrics AI are for educational and risk-management purposes only. Always consult a certified financial advisor before committing capital.
          </p>
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-xl bg-slate-900 border border-white/10 text-[11px] text-slate-300">
            <Lock className="w-3.5 h-3.5 text-emerald-400" />
            <span>Bank-Grade 256-Bit SSL Data Encryption</span>
          </div>
        </div>

      </div>

      <div className="max-w-7xl mx-auto pt-6 border-t border-white/5 flex flex-col sm:flex-row items-center justify-between text-xs text-slate-500 gap-4">
        <p>© 2026 CredoMetrics AI Inc. All rights reserved.</p>
        <div className="flex items-center gap-6">
          <a href="#" className="hover:text-slate-300">Privacy Policy</a>
          <a href="#" className="hover:text-slate-300">Terms of Advisory</a>
          <a href="#" className="hover:text-slate-300">API Status</a>
        </div>
      </div>
    </footer>
  );
}
