import React from 'react';
import { Sparkles, ShieldCheck, Lock, Cpu } from 'lucide-react';

export default function Footer({ setActiveTab }) {
  return (
    <footer className="mt-16 border-t border-[var(--border-card)] bg-[var(--bg-card)] text-[var(--text-muted)] py-12 px-4 lg:px-8">
      <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
        
        {/* Col 1 */}
        <div className="md:col-span-2">
          <div className="flex items-center gap-2.5 mb-3">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-indigo-600 to-pink-500 flex items-center justify-center shadow-sm">
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <span className="font-extrabold text-xl text-[var(--text-main)] font-['Outfit'] uppercase tracking-wider">CREDOMETRICS AI</span>
          </div>
          <p className="text-xs text-[var(--text-muted)] max-w-md leading-relaxed mb-4 font-medium">
            Next-generation Gen-AI WealthTech platform. Transforming social media hype, finfluencer noise, and fragmented investments into personalized, actionable risk profiling, net worth tracking, and goal-based SIP advisory.
          </p>
          <div className="flex items-center gap-4 text-xs font-semibold">
            <span className="flex items-center gap-1.5 text-emerald-500 font-bold">
              <ShieldCheck className="w-4 h-4" /> SEC/SEBI Framework Aligned
            </span>
            <span className="flex items-center gap-1.5 text-indigo-500 font-bold">
              <Cpu className="w-4 h-4" /> Groq LLM Inference Engine
            </span>
          </div>
        </div>

        {/* Col 2 */}
        <div>
          <h4 className="text-sm font-bold text-[var(--text-main)] mb-3 font-['Outfit']">Platform Navigation</h4>
          <ul className="space-y-2 text-xs font-semibold">
            <li>
              <button onClick={() => setActiveTab('landing')} className="text-[var(--text-muted)] hover:text-indigo-500 transition-colors">
                Landing & Feature Overview
              </button>
            </li>
            <li>
              <button onClick={() => setActiveTab('dashboard')} className="text-[var(--text-muted)] hover:text-indigo-500 transition-colors">
                Consolidated Portfolio Tracker
              </button>
            </li>
            <li>
              <button onClick={() => setActiveTab('analyzer')} className="text-[var(--text-muted)] hover:text-emerald-500 transition-colors">
                AI Social Hype Analyzer
              </button>
            </li>
            <li>
              <button onClick={() => setActiveTab('goals')} className="text-[var(--text-muted)] hover:text-pink-500 transition-colors">
                Goal SIP Calculator & Advisory
              </button>
            </li>
          </ul>
        </div>

        {/* Col 3 */}
        <div>
          <h4 className="text-sm font-bold text-[var(--text-main)] mb-3 font-['Outfit']">Security & Compliance</h4>
          <p className="text-xs text-[var(--text-muted)] leading-relaxed mb-3 font-medium">
            Financial analytics generated by CredoMetrics AI are for educational and risk-management purposes only. Always consult a certified financial advisor before committing capital.
          </p>
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-xl bg-[var(--bg-card-inner)] border border-[var(--border-card)] text-[11px] text-[var(--text-main)] font-semibold shadow-sm">
            <Lock className="w-3.5 h-3.5 text-emerald-500" />
            <span>Bank-Grade 256-Bit SSL Data Encryption</span>
          </div>
        </div>

      </div>

      <div className="max-w-7xl mx-auto pt-6 border-t border-[var(--border-card)] flex flex-col sm:flex-row items-center justify-between text-xs text-[var(--text-muted)] gap-4 font-medium">
        <p>© 2026 CredoMetrics AI Inc. All rights reserved.</p>
        <div className="flex items-center gap-6">
          <a href="#" className="hover:text-[var(--text-main)] transition-colors">Privacy Policy</a>
          <a href="#" className="hover:text-[var(--text-main)] transition-colors">Terms of Advisory</a>
          <a href="#" className="hover:text-[var(--text-main)] transition-colors">API Status</a>
        </div>
      </div>
    </footer>
  );
}
